### ISSUE TITLE
Update copyright information

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/OBAKit#161]
- [ ] Update `LICENSE` with a copyright assignment to OTSF.
- [ ] Update all copyright headers in the app to use the text below.
- [ ] Make Xcode generate a consistent copyright header (use the text below).

```
/*
 * Copyright (c) Open Transit Software Foundation
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
```

**Comment by morrme** [comment]
@aaronbrethorst do you still need help with this?

**Comment by aaronbrethorst** [comment]
@morrme this does still need to be done, yes!

**Comment by morrme** [comment]
@aaronbrethorst I think I can take on items 1 and 2, if that will help.

**Comment by aaronbrethorst** [comment]
@morrme yep, most definitely and thank you!

**Comment by morrme** [comment]
@aaronbrethorst 
You want to keep the 
`Created by Aaron Brethorst on 6/23/19.`
And just add the copyright and license text below it, correct?

**Comment by aaronbrethorst** [comment]
I would actually rather get rid of the created by {NAME} on {DATE} text.
