### ISSUE TITLE
text size does not always adjust

### ISSUE THREAD

**Issue by alanborning** [OneBusAway/OBAKit#207]
There is an accessibility setting on the iPhone to change the text size (for example to make it larger for low vision folks).  Unfortunately only some parts of the interface account for the change.  See attached screenshot, in which the arrival times are (correctly) larger, but the items under "More options" are not.  There are lots of other places with this problem in the interface.

To reproduce: go to Settings / Accessibility / Display & Text Size.
Turn on Larger accessibility sizes, and also move the slider at the bottom of the screen to a larger text size.

![IMG_3271](https://user-images.githubusercontent.com/918773/83186462-645b1d00-a0e1-11ea-8198-d1fdae16febe.png)

**Comment by ualch9** [comment]
Moved to [Accessibility for Launch](https://github.com/OneBusAway/OBAKit/projects/3).
