### ISSUE TITLE
problem accessing San Diego with current build 20.2.0 (20200617.0)

### ISSUE THREAD

**Issue by alanborning** [OneBusAway/OBAKit#214]
I tried switching the region to San Diego and am seeing an error "Expected to receive JSON data from the server, but we received (nil) instead."  See attached.

![IMG_3324](https://user-images.githubusercontent.com/918773/84943508-4efe6080-b099-11ea-8f3e-fc9cf0c8d10a.PNG)

**Comment by ualch9** [comment]
I don't get this problem anymore, this was probably fixed a bit ago.
