### ISSUE TITLE
Network operation failures never passed to the caller

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/OBAKit#271]
Consider the following ([actual](https://github.com/OneBusAway/OBAKit/blob/b56f26fdef506b2b887e2bf7a4c18b8545ddee75/OBAKit/Stops/StopViewController.swift#L305-L330)):
```swift
let op = apiService.getArrivalsAndDeparturesForStop(id: stopID, minutesBefore: minutesBefore, minutesAfter: minutesAfter)
op.complete { result in
    switch result {
    case .failure:
        print(":(")
    case .success:
        print(":)")
    }
}

self.operation = op
```

The closure will never reach a `failure` result. Although the error is caught somewhere earlier in the chain, it won't be passed  to the `complete` closure. I noticed in the console that the network operation is retried, but I think the error should still be passed into the closure regardless.

@aaronbrethorst Is this design intentional?

**Comment by aaronbrethorst** [comment]
no, not intentional.
