### ISSUE TITLE
VoiceOver 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/OBAKit#29]

**Comment by aaronbrethorst** [comment]
Hey @ualch9 - I'm assigning this task to you because you've been most plugged-in on what's happening with VoiceOver support in the app. I was looking through https://github.com/OneBusAway/OBAKit/projects/3, and it appears that some of these tasks are complete, some are post-launch, and some are still real live issues that need to be fixed before release. Could you open issues on what remains, even if they are as general as 'validate that VoiceOver works correctly on screen X'? That way I can pick up tasks without worrying about duplicating effort. thank you :)

**Comment by ualch9** [comment]
Sure, I’ll open tasks either tonight or tomorrow.

— alan
________________________________

**Comment by ualch9** [comment]
Opened #428, #429, #430, #431.

**Comment by ualch9** [comment]
@aaronbrethorst I've opened voiceover issues needed for Release. I may not have much free time over the next several weeks, but if I do, I'll be sure to assign stuff to myself before I work to avoid dupe work.

**Comment by aaronbrethorst** [comment]
Sounds great, @ualch9. Thanks for opening up all of these tasks!
