### ISSUE TITLE
Make all models conform to Identifiable

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/OBAKit#292]
I suspect this'll be helpful in the future, and it'll be a lot easier to do now than it will be once the app is in the wild.

https://developer.apple.com/documentation/swift/identifiable

https://nshipster.com/identifiable/

**Comment by aaronbrethorst** [comment]
@ualch9 please be sure to grab tickets when you work on them so that we don't double up effort.

**Comment by ualch9** [comment]
oops i didn't notice 😬

**Comment by aaronbrethorst** [comment]
Fixed with https://github.com/OneBusAway/OBAKit/pull/293
