### ISSUE TITLE
"Load more" overlaps the date&time frame information on Stop Page

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/OBAKit#365]
Upon first load of stop view, the "load more" button overlaps the date&time frame information.

It only happens on first load of that UI.

See screenshot (it's in polish language, but same applies to english version):

![image](https://user-images.githubusercontent.com/2254/118035947-ca57a900-b320-11eb-936f-2611c172b639.png)

**Comment by aaronbrethorst** [comment]
@ualch9 do you have any bandwidth to look into this?

**Comment by ualch9** [comment]
@wkulesza I have a fix in c9d6296. please check if it works for you.

**Comment by ualch9** [comment]
continued in #415
