### ISSUE TITLE
Big distance between stop and user location on map - while in manual region selection

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/OBAKit#366]
When in Stop Page and long pressing a row (with route arrival info), a popup appears that allows to add an alarm, add a bookmark and share that trip. Above this, map zooms out to show that stop and user current location.
This is great, when automatic region selection in enabled, but when user selected region manually, this might not work as planned.

See below screenshot - stop and current user location are well spread and not giving anything useful to user.

Perhaps, in case of manual region selection, don't show this map zoom level, but instead show zoom at city/region level ?

![image](https://user-images.githubusercontent.com/2254/118038107-8ca84f80-b323-11eb-9197-f7c4600b0442.png)

**Comment by aaronbrethorst** [comment]
My first instinct is if the user's current location happens to fall outside of the stop's region's bounds, then don't use the user's location and the vehicle's location as the bounding box for the trip controller's map view. In that case, behave as if the user's location is unavailable.

**Comment by ualch9** [comment]
> ...if the user's current location happens to fall outside of the stop's region's bounds...

I don't think we should include the user's location at all. A personal use case for me, I am browsing a bus route in Seattle but the map expands to include my location in Bellevue, which is irrelevant to me.

**Comment by aaronbrethorst** [comment]
@ualch9 i think your approach sounds good.
