### ISSUE TITLE
Vehicle Info is busted?

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/OBAKit#417]
From a beta user in Puget Sound:

> Trying to look up my bus’s info, but getting an error 500.

![image](https://user-images.githubusercontent.com/2254/125318260-4fe6dd80-e2ff-11eb-8c76-dde0f3513a61.png)

**Comment by ualch9** [comment]
is this screenshot from the user?

**Comment by aaronbrethorst** [comment]
> is this screenshot from the user?

Yep.

**Comment by aaronbrethorst** [comment]
Fixed with https://github.com/OneBusAway/onebusaway-deep-links/commit/96dca3a5195d11f0de14bd1b4db18a0188202c99 and https://github.com/OneBusAway/onebusaway-deep-links/commit/673e05edac5969f7bc97627a705ef7b8ea0e513b
